package br.org.unesco.model;
// Generated Jan 7, 2016 4:12:20 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TbMunicipiosIbge generated by hbm2java
 */
@Entity
@Table(name = "TB_MUNICIPIOS_IBGE", schema="appesca")
public class MunicipiosIbge implements java.io.Serializable {

	private static final long serialVersionUID = 8297494606786626460L;

	private int codigo;
	private String municipio;
	private String uf;
	private IdentEntrevistado entrevistado;

	public MunicipiosIbge() {
	}

	public MunicipiosIbge(int codigo) {
		this.codigo = codigo;
	}

	public MunicipiosIbge(int codigo, String municipio, String uf) {
		this.codigo = codigo;
		this.municipio = municipio;
		this.uf = uf;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "municipio", length = 50)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "uf", length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}
	
	@OneToOne(mappedBy = "municipio")
	public IdentEntrevistado getEntrevistado() {
		return entrevistado;
	}

	public void setEntrevistado(IdentEntrevistado entrevistado) {
		this.entrevistado = entrevistado;
	}

}
